### PR TITLE
add more info

### PR DESCRIPTION
**Pull request by bentoavb**
Hello

This is a pull request to add more information from the noembed.com API, such as a link to the thumbnail image.

Thank you

### CODE REVIEW

**Comment by chickenshitretard** [comment]
.to_dict() returns a list, not a dict

**Comment by w-henderson** [comment]
This is a good idea but it should be an optional parameter because it does take like 150-200ms longer per result for the call, so users looking for efficiency over detail wouldn't want it forced on them.

**Comment by bentoavb** [comment]
Thank you for the advice. I added a parameter to define this functionality as optional.

**Comment by joetats** [comment]
Awesome! Let me test this out a bit tonight and I'll get it merged and added to the package.

**Comment by joetats** [comment]
Going to reject this at the moment as the new HTML requires a different parsing to complete. Might be worth updating to include the additional info as an optional parameter in the future

**Pull request closed without merging**
